name: Push Branch

# trigger on pushes to main
on:
  push:
    branches:
      - main

jobs:
  push_job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.ref }} has been pushed
        echo sha before: ${{ github.event.before }}
        echo sha after: ${{ github.event.after }}
        echo latest commit sha: ${{ github.event.commits[0][id] }}
        echo latest commit message: ${{ github.event.commits[0][message] }}
